petl:
  homeDir: "/home/mseaton/environments/malawi-consolidated-example"
  datasourceDir: "${petl.homeDir}/datasources"
  jobDir: "${petl.homeDir}/jobs"
  startup:
    jobs:
      - "refresh-full.yml"

server:
  port: 9109

logging:
  level:
    root: "WARN"
    org.pih: "DEBUG"

upperNenoOpenmrs:
  host: "localhost"
  port: "3308"
  databaseName: "neno"
  user: "root"
  password: "root"

lowerNenoOpenmrs:
  host: "localhost"
  port: "3308"
  databaseName: "lisungwi"
  user: "root"
  password: "root"

upperNenoReporting:
  host: "localhost"
  port: "3308"
  databaseName: "neno_reporting"
  user: "root"
  password: "root"
  options: "autoReconnect=true&sessionVariables=default_storage_engine%3DInnoDB&useUnicode=true&characterEncoding=UTF-8"

lowerNenoReporting:
  host: "localhost"
  port: "3308"
  databaseName: "lisungwi_reporting"
  user: "root"
  password: "root"
  options: "autoReconnect=true&sessionVariables=default_storage_engine%3DInnoDB&useUnicode=true&characterEncoding=UTF-8"

consolidatedReporting:
  host: "localhost"
  port: "1433"
  databaseName: "openmrs_reporting"
  user: "sa"
  password: "9%4qP7b2H!%J"
