petl:
  homeDir: "<specify>"
  datasourceDir: "${homeDir}/datasources"
  jobDir: "${homeDir}/jobs"
  startup:
    jobs:
      - "initialize.yml"
      - "load-encounters.yml"

mysql:
  host: "<specify>"
  port: "<specify>"
  databaseName: "<specify>"
  user: "<specify>"
  password: "<specify>"
  options: "autoReconnect=true&sessionVariables=default_storage_engine%3DInnoDB&useUnicode=true&characterEncoding=UTF-8&serverTimezone=US/Eastern"

sqlserver:
  host: "localhost"
  port: "1433"
  databaseName: "openmrs_reporting"
  user: "sa"
  password: "<specify>"

server:
  port: 9109
  
logging:
  level:
    root: "WARN"
    org.pih: "DEBUG"
