# For every commit pushed to the master branch, or any change detected to dependencies in Maven,
# this will compile, package, test, and verify the master branch.

name: Build and Test

on:
  push:
    branches: ['master']

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 8
      - name: Maven Verify
        run: mvn -B verify --file pom.xml
