name: Build with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Maven Action
      uses: s4u/setup-maven-action@v1.18.0
      with:
        java-version: 8
        maven-version: '3.6.3'
    - name: Build with Maven
      id: build_with_maven
      run: |
        mvn clean install --batch-mode --file pom.xml