name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Local Maven Repository
      id: setup_local_maven_repository
      run: |
        ./create-local-maven-repo.sh

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 8
        cache: 'maven'
        server-id: central
        server-username: SONATYPE_USERNAME
        server-password: SONATYPE_PASSWORD
        gpg-private-key: ${{ secrets.SONATYPE_GPG_PRIVATE_KEY }}
        gpg-passphrase: SONATYPE_GPG_PASSPHRASE

    # Set up git config
    - name: Setup Git Config
      run: |
        git config user.name "Github Action"
        git config user.email "github-action@users.noreply.github.com"

    - name: Deploy release
      run: mvn -B release:prepare release:perform -Prelease --file pom.xml
      env:
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        SONATYPE_GPG_PASSPHRASE: ${{ secrets.SONATYPE_GPG_PASSPHRASE }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}