services:

  mysql:
    image: library/mariadb:11.8
    environment:
      - MYSQL_ROOT_PASSWORD=root
    command: "mariadbd \
              --innodb_default_row_format=DYNAMIC \
              --character-set-server=utf8 \
              --collation-server=utf8_general_ci \
              --character-set-collations=utf8mb3=utf8mb3_general_ci \
              --max_allowed_packet=1G \
              --innodb-buffer-pool-size=2G \
              --user=mysql \
              --server-id=1 \
              --skip-log-bin \
              --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
    volumes:
      - "mysql_data:/var/lib/mysql"
    ports:
      - "3308:3306"

volumes:
  mysql_data:

networks:
  default:
    name: "openmrs"
    external: "true"
